### ISSUE TITLE
Add a way to make POST requests passing a body

### ISSUE THREAD

**Issue by rocboronat** [arduino-libraries/UnoWiFi-Developer-Edition-Lib#2]
I made some searches on Google and it seems that everyone is stuck on same place: sending the post body in a post request and not just url params in its url.

Now, looking at the source code, it seems that the function doesn't exist... :·(

So... there's any way to do it?

Thanks for you work!

**Comment by sergiotomasello** [comment]
no @rocboronat, there's no way to do that :/

**Comment by rocboronat** [comment]
Sad :·( hehe please, notify me if we can do it at some point of the future! :·) Thanks for the answer! We will find a workaround. The bad part is that we can't use great pure REST endpoints. Oooh.

CC @mpous

**Comment by sergiotomasello** [comment]
we are working on a new firmware (esp8266) for the arduino uno wifi developer edition that allows  a [standard wifi-like](http://www.arduino.org/learning/reference/WiFi) approach. even most of all libraries based on it should work trasparently...

**Comment by rocboronat** [comment]
It will be really great. I fell in love with the seamless way to setup the board, but I don't get the way to just read a value from a GET request. It seems that Ciao has some automations that does magic... and having a just wifi-like behavior will be great.

Again: Thanks for your work, @sergiotomasello :·)
