### ISSUE TITLE
low power state

### ISSUE THREAD

**Issue by Sverik** [arduino-libraries/UnoWiFi-Developer-Edition-Lib#5]
Currently the powerON and powerOFF functions in ArduinoWifiClass are stubs, empty. Are there any plans to implement those? Is there perhaps a workaround for turning off WiFi to conserver power?

**Comment by alfran** [comment]
I'm sorry, but the ATmega328p can't manage the power state of ESP8266 due to electrical design.
This mean that is not possible and it will not possible to turning off the WiFi by using the library. 

Regards.
